# Generated by Django 5.1.1 on 2024-11-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantes',
            name='latitud_map',
        ),
        migrations.RemoveField(
            model_name='restaurantes',
            name='longitud_map',
        ),
    ]
