# Generated by Django 5.1.1 on 2024-11-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendario',
            old_name='dia',
            new_name='dia_evento',
        ),
        migrations.RenameField(
            model_name='calendario',
            old_name='restaurante_id',
            new_name='restaurante',
        ),
        migrations.AddField(
            model_name='calendario',
            name='dia_semana',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
