# Generated by Django 5.1.1 on 2024-09-25 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tipousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=225, unique=True)),
                ('contrasena', models.CharField(max_length=200)),
                ('id_tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipousuario')),
            ],
        ),
    ]
