# Generated by Django 5.1.1 on 2024-10-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_calendario_calificaciones_canton_distrito_favoritos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='url_img',
            field=models.URLField(max_length=500),
        ),
    ]
