# Generated by Django 5.1.1 on 2024-11-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_restaurantes_latitud_map_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantes',
            name='coordenadas',
        ),
        migrations.AddField(
            model_name='restaurantes',
            name='latitud_map',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantes',
            name='longitud_map',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
