# Generated by Django 5.1.1 on 2024-10-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_calendario_calificaciones_canton_distrito_favoritos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='alta_demanada',
        ),
        migrations.AddField(
            model_name='calendario',
            name='tipo',
            field=models.CharField(choices=[('alta_demanda', 'Alta Demanda'), ('evento', 'Evento'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
    ]
