# Generated by Django 5.1.1 on 2024-10-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_imagenes_url_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='tipo_imagen',
            field=models.CharField(choices=[('perfil', 'Perfil'), ('encabezado', 'Encabezado'), ('galeria', 'Galería')], max_length=20),
        ),
    ]
