# Generated by Django 5.1.1 on 2024-10-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_calendario_alta_demanada_calendario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platillos_destacados',
            name='id_imagen',
        ),
        migrations.AddField(
            model_name='platillos_destacados',
            name='url_img_platillo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
