# Generated by Django 5.1.1 on 2024-09-25 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_restaurantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='calificaciones',
            fields=[
                ('calificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('restaurante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurantes')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
        ),
    ]
