# Generated by Django 5.1.1 on 2024-10-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_imagenes_tipo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='tipo_imagen',
            field=models.CharField(blank=True, choices=[('perfil', 'Perfil'), ('encabezado', 'Encabezado'), ('galeria', 'Galería')], max_length=20, null=True),
        ),
    ]
