# Generated by Django 5.1.1 on 2024-10-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_platillos_destacados_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillos_destacados',
            name='nombre_platillo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
