# Generated by Django 5.1.1 on 2024-10-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_imagenes_tipo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='url_logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
