# Generated by Django 5.1.1 on 2024-10-31 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_platillos_destacados_nombre_platillo'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_restaurantes',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('pagina_1', models.URLField(blank=True, max_length=500, null=True)),
                ('pagina_2', models.URLField(blank=True, max_length=500, null=True)),
                ('pagina_3', models.URLField(blank=True, max_length=500, null=True)),
                ('pagina_4', models.URLField(blank=True, max_length=500, null=True)),
                ('pagina_5', models.URLField(blank=True, max_length=500, null=True)),
                ('pagina_6', models.URLField(blank=True, max_length=500, null=True)),
                ('pagina_7', models.URLField(blank=True, max_length=500, null=True)),
                ('pagina_8', models.URLField(blank=True, max_length=500, null=True)),
                ('restaurante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurantes')),
            ],
        ),
    ]
