# Generated by Django 5.1.1 on 2024-10-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_platillos_destacados_nombre_platillo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantes',
            name='latitud_map',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantes',
            name='longitud_map',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
