# Generated by Django 5.1.1 on 2024-10-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_imagenes_url_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='url_logo',
        ),
    ]
