# Generated by Django 5.1.1 on 2024-10-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuarios_is_staff'),
        ('api', '0008_remove_imagenes_url_logo'),
    ]

    operations = [
    ]
