# Generated by Django 5.1.1 on 2024-10-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_menu_restaurantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantes',
            name='coordenadas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
