# Generated by Django 5.1.1 on 2024-10-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_restaurantes_latitud_map_restaurantes_longitud_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantes',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
