# Generated by Django 5.1.1 on 2024-10-31 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_restaurantes_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platillos_destacados',
            name='nombre_platillo',
        ),
    ]
