# Generated by Django 5.1.1 on 2024-10-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20241029_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='url_header',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
