# Generated by Django 5.1.1 on 2024-10-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_imagenes_url_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantes',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantes',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
